

## 3. ?�Y L� PH?N QUAN TR?NG: Xu?t to�n b? SQL ra file latest_schema.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/resources/latest_schema.sql
#spring.jpa.properties.hibernate.format_sql=true



spring.application.name=library-manager

spring.datasource.url=jdbc:mysql://localhost:3306/library_manager?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
# Đảm bảo KHÔNG có bất kỳ ký tự nào (kể cả dấu cách) sau dấu bằng
spring.datasource.password=

# Tạm thời tắt Flyway để tránh lỗi initializer
spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=update